LANG = "LC_ALL=en_US.utf8 LANG=en_US.utf8"

rule qc_dna__multiqc:
  input:
    fastqcs    = pipeman.input(
                   fastq_qc__readZip, 
                   derefKwargs=['sample_name',]),
    mdMetrics  = pipeman.input(
                   f"{bam__sampleTarget}.metrics",
                   derefKwargs=['sample_name',]),
    hsMetrics  = pipeman.input(
                   f"{bam__sampleTarget}_hsMetrics.txt",
                   derefKwargs=['sample_name',]),
    flagstat   = pipeman.input(
                   f"{bam__sampleTarget}_flagstat.txt",
                   derefKwargs=['sample_name',])
  output:
    report   =           f"{bam__pipeTarget}multiqc_report.html",
    data     = directory(f"{bam__pipeTarget}multiqc_data")
  run:
    outDir = bam__pipeTarget.format(**wildcards)
    cmd  = f"""
      {LANG} multiqc       \
        -f                 \
        -o {outDir}        \
        {input} 
    """
    exshell(**vars())

ruleorder: qc_dna__multiqc > samples__all > samples__runs
