LANG = "LC_ALL=en_US.utf8 LANG=en_US.utf8"

rule qc_rnaseq__multiqc:
  input:
    fastqcs   = lambda wildcards: pipeman.samples.map(
      fastq_qc__readZip, 
      derefKwargs=['sample_name',],
      **wildcards),
    inferExp  = lambda wildcards: pipeman.samples.map(
      f"{bam__sampleTarget}.inferExperiment",
      derefKwargs=['sample_name',],
      **wildcards),
    bamCounts = lambda wildcards: pipeman.samples.map(
      f"{bam__sampleTarget}.counts.summary",
      derefKwargs=['sample_name',],
      **wildcards),
    bamstat    = lambda wildcards: pipeman.samples.map(
      f"{bam__sampleTarget}.bamstats",
      derefKwargs=['sample_name',],
      **wildcards),
    readsDist  = lambda wildcards: pipeman.samples.map(
      f"{bam__sampleTarget}.reads_distribution",
      derefKwargs=['sample_name',],
      **wildcards)
  output:
    report   =           f"{bam__pipeTarget}multiqc_report.html",
    data     = directory(f"{bam__pipeTarget}multiqc_data")
  run:
    outDir = bam__pipeTarget.format(**wildcards)
    cmd  = f"""
      {LANG} multiqc       \
        -f                 \
        -o {outDir}        \
        {input} 
    """
    exshell(**vars())

ruleorder: qc_rnaseq__multiqc > samples__all > samples__runs
