include: "rseqc.py"

rule rseqc__inferExperiment:
  input:
    bam = "{someprefix}/{sample_name}.bam",
    bai = "{someprefix}/{sample_name}.bai",
    bed = lambda x: gencode__bed()
  output: 
    inf = "{someprefix}/{sample_name}.inferExperiment"
  run:
    cmd = """
      infer_experiment.py \
        -r {input.bed}    \
        -i {input.bam}    \
        -s 5000000        \
       > {output.inf}
    """
    exshell(**vars())

rule rseqc__readsDistribution:
  input:
    bam  = "{someprefix}/{sample_name}.bam",
    bai  = "{someprefix}/{sample_name}.bai",
    bed  = lambda x: gencode__bed()
  output:
    dist = "{someprefix}/{sample_name}.reads_distribution"
  run:
    cmd = """
      read_distribution.py \
        -i {input.bam}      \
        -r {input.bed}      \
       > {output.dist}
    """
    exshell(**vars())
