include: "rseqc.py"

rule rseqc__inferExperiment:
  input:
    bam = "{someprefix}/{sample_name}.bam",
    bai = "{someprefix}/{sample_name}.bai",
    bed = lambda x: annot__ebiBed()
  output: 
    inf = "{someprefix}/{sample_name}.inferExperiment"
  run:
    cmd = """
      infer_experiment.py \
        -r {input.bed}    \
        -i {input.bam}    \
        -s 200000000      \
       > {output.inf}
    """
    exshell(**vars())

rule rseqc__readDistribution:
  input:
    bam  = "{someprefix}/{sample_name}.bam",
    bai  = "{someprefix}/{sample_name}.bai",
    bed  = lambda x: f"{annot__ucscBed()}"
  output:
    dist = "{someprefix}/{sample_name}.read_distribution"
  run:
    cmd = """
      read_distribution.py  \
        -i {input.bam}      \
        -r {input.bed} \
       > {output.dist}
    """
    exshell(**vars())
