include: "bwa.py"

ruleorder: mapping__sortSamplePicard > mapping__sortSampleSamtools > mapping_bwa__alignReads
rule mapping_bwa__alignReads:
  input: 
    configs = config__config_files,
    reads_1 = lambda wildcards: fastq__mapStringSamples(
                fastq_merge__read, sample_read="R1", **wildcards),
    reads_2 = lambda wildcards: fastq__mapStringSamples(
                fastq_merge__read, sample_read="R2", **wildcards)
  output:
    primary   = mapping__sample
  run:
    cmd = """
      bwa mem               \
        -R "{readGroup}"    \
        -t {bwa.cores}      \
        {bwaGenomeIndex}    \
        {reads}             \
        > {output.primary}
    """
    exshell(
      input, output, cmd, **wildcards,
      readGroup = mapping__sampleReadGroup(wildcards),
      bwa = pipeman.config.pipeline.modules.mapping.aligner,
      bwaGenomeIndex = mapping_bwa__genomeIndex(),
      reads = mapping_bwa__readsToString(input.reads_1, input.reads_2)
    )
