include: 'project.py'
include: 'lims.sk'

project__config = 'config/project.json'
pipeman.addConfigFiles(project__config)

# -----------------
# Project Metadata
# -----------------
rule project__config:
  output: 
    file = project__config
  run:
    cmd = f"""
      curl                                         \
        "{config_lims__URL_PRJ}/{pipeman.project}.json" \
       > {output.file}
    """
    exshell(**vars())

localrules: project__config
