samples__dir       = "samples/{sample_name}"
samples__files     = "samples/samples.txt"
samples__csvMap    = pypette.samples.configManager.configfileBase + "{extension}"
samples__csvMapDft = pypette.samples.configManager.configFileDefault

pypette.includeModules(
  "fastq/fastq.py",
  "config/runs.py")

rule samples__files:
  """
  Find all the fastq files in the RUN directories specified in the 
  configuration.
  """
  input:
    confs   = config__files,
    project = project__config
  output: 
    file    = samples__files
  run:
    runs    = " ".join(runs__projectPaths(pypette.project))
    cmd     = f"""
      find -L {runs} -maxdepth 2 -name '*.fastq.gz' > {output.file}
    """
    exshell(force=True, **vars())

rule samples__map:
  """   
  Maps all the illumina filenames' metadata in a file.
  """
  input: 
    file = samples__files
  output: 
    file = samples__csvMap
  run:
    """ File Output Header """
    sampleLines = [ FastqFile.fieldNames() ]
    with open(input.file, 'r') as fqFiles:
      """ Mapped Samples Lines """
      sampleLines.extend([ f for f in map(fastq__mapFilename, fqFiles) if f ])

    """ Write Output """
    with open(output.file, 'a') as fmap:
      fmap.write(
        pypette.samples.listsToSamplesheet(
          sampleLines, 
          pypette.sampleExtensions[wildcards.extension]))
    exshell(force=True, **vars())
