include: 'lims.sk'
include: 'seqrun.py'

seqrun__config = 'config/run.json'
pipeman.addConfigFiles(seqrun__config)

# -----------------
# Project Metadata
# -----------------
rule seqrun__config:
  output: 
    file = seqrun__config
  run:
    cmd = """
      curl                                         \
	"{config_lims__URL_SEQRUN}/{pipeman.project}.json" \
       > {output.file}
    """
    shell(cmd)
    pipeman.configManager.loadConfig(output.file)
