include: "samples.py"

rule sample:
  """
  Presents a sample.
  """
  output: "{p}.sample"
  run:
    print(msgPoke(pypette.samples.queryFirstNameOrId(wildcards.p)))
    open(output[0], 'a').close()

rule evol:
  """
  Describes an evolution.
  """
  input: "{p}.sample"
  output: "{p}.evol"
  run:
    print(msgEvol(pypette.samples.queryFirstNameOrId(wildcards.p)))
    open(output[0], 'a').close()

rule evols:
  """
  Describes all evolutions.
  """
  input: "{p}.sample"
  output: "{p}.evols"
  run:
    print(msgEvols(pypette.samples.queryFirstNameOrId(wildcards.p)))
    open(output[0], 'a').close()

rule supids:
  """
  Retrieves all samples with sample_id > {id} in target '{id}.supids'.
  """
  output: "{p}.supids"
  run:
    print(pypette.samples.query("sample_id>{}".format(wildcards.p)))
    open(output[0], 'a').close()
    
pypette.toClean("*.sample", "*.evol", "*.evols", "*.supids")
