include: 'bam.py'
pipeman.includeModules(
  "genomes/genome.sk",
  "genomes/annotation.sk",
  "genomes/exome.sk")

""" Allowed Sorting Processes """
sortingTools = ('picard', 'samtools')
pipeman.updateWildcardConstraints(
  procSorted    = "(sorted/({})/)?".format("|".join(sortingTools)),
  procMarkDup   = "(markdup/)?",
  procBamMerged = "(merged/)?"
)

""" Sample Run Reads Output Targets """
pipeman.addTargets(
  bam_mapper__dir          = f"mapped/{bam__alignerDir()}",
  bam_mapper__pipeTarget   = "{fastq__pipeTarget}{bam_mapper__dir}",
  bam_mapper__sampleTarget = "{bam_mapper__pipeTarget}/{{sample_name}}",

  bam__procs        = "{{procBamMerged}}{{procSorted}}{{procMarkDup}}",
  bam__pipeTarget   = "{bam_mapper__pipeTarget}/{bam__procs}",
  bam__sampleTarget = "{bam__pipeTarget}{{sample_name}}",
  bam__sample       = "{bam_mapper__sampleTarget}.bam" )

# Note: Include the aligner module found in pipeline configuration file after this
#       file's variables, as aligner's rules should depend on the variables 
#       declared above.
bam__includeAlignerModule()

# -----------------
# Mark Duplicates
# -----------------
bam__sampleMarkdupPrefix = "{anyprefix}markdup/{sample_name}"
rule bam__markDuplicates:
  input: 
    bam     = "{anyprefix}{sample_name}.bam"
  output: 
    bam     = pipeman.temp(f"{bam__sampleMarkdupPrefix}.bam"    ),
    bai     = pipeman.temp(f"{bam__sampleMarkdupPrefix}.bai"    ),
    metrics =      f"{bam__sampleMarkdupPrefix}.metrics"
  run:
    cmd = """
      picard MarkDuplicates                           \
      I={input.bam}                                   \
      O={output.bam}                                  \
      CREATE_INDEX=true                               \
      VALIDATION_STRINGENCY=SILENT                    \
      REMOVE_DUPLICATES=false                         \
      ASSUME_SORTED=true                              \
      METRICS_FILE={output.metrics}                    
    """
    exshell(**vars())

ruleorder: bam__markDuplicates > bam__makeIndex > samples__runs

# --------------
# Sorting Bams
# --------------
rule bam__sortSamplePicard:
  input:  "{anyprefix}{sample_name}.bam"
  output: pipeman.temp("{anyprefix}sorted/picard/{sample_name}.bam"),
  run:
    cmd = """
      picard SortSam          \
        I={input}             \
        SORT_ORDER=coordinate \
        O={output}
    """
    exshell(**vars())

rule bam__sortSampleSamtools:
  input:  "{anyprefix}{sample_name}.bam"
  output: pipeman.temp("{anyprefix}sorted/samtools/{sample_name}.bam")
  run:
    bwa = pipeman.config.pipeline.modules.mapping.aligner
    cmd = """
      samtools view          \
        -Su {input}          \
    | samtools sort          \
        -T {output.bam}.tmp  \
        -@ {bwa.cores}       \
        -o {output.bam}      \
        -
    """
    exshell(**vars())

ruleorder: samples__runs > bam__sampleStats > bam__sortSampleSamtools > bam__markDuplicates

# -----------
# Bam Stats
# -----------
rule bam__sampleStats:
  input:
    bam   = "{someprefix}.bam"
  output:
    stats = "{someprefix}.bamstats"
  run:
    cmd = """
      bamtools stats       \
        -in {input.bam}    \
        > {output.stats}
    """
    exshell(**vars())

ruleorder: samples__all > bam__sampleStats

# ------------
# Merge BAMs
# ------------
ruleorder: bam__markDuplicates > bam__sortSamplePicard > bam__sortSampleSamtools > bam__mergeSample
rule bam__mergeSample:
  input:
    bam = pipeman.input(
            bam__sample, 
            derefKwargs = ['sample_run',],
            withResult=True)
  output:
    bam = pipeman.temp("samples/{sample_name}/runs/{sample_run}/fastq/" + fastq__procs + bam_mapper__dir + "/merged/{sample_name}.bam")
  run:
    if len(input.bam) > 1:
      mergePrefixes = picardMergeInputString(input.bam)
      cmd = """
        picard MergeSamFiles                            \
          {mergePrefixes}                               \
          O={output.bam}                                \
          CREATE_INDEX=true                             \
          MSD=true                                      \
          TMP_DIR=$TMPDIR                               \
          VALIDATION_STRINGENCY=SILENT                  \
         > {output.bam}.log
      """
    else:
      cmd = """
        ln {input.bam} {output.bam}
      """
    exshell(**vars())

ruleorder: samples__runs > bam__mergeSample 

rule bam__makeIndex:
  input:       
         "{someprefix}.bam"
  output: 
    pipeman.temp("{someprefix}.bai")
  run:
    cmd = """
      picard BuildBamIndex I={input} O={output}
    """
    exshell(**vars())

rule bam__hsMetrics:
  input:  
    "{someprefix}.bam"
  output: 
    "{someprefix}_hsMetrics.txt"
  run:
    genomeFasta     = genome__fasta()
    baitIntervals   = exome__baitIntervals()
    targetIntervals = exome__targetIntervals()
    cmd = """
      picard CollectHsMetrics          \
        BI={baitIntervals}             \
        TI={targetIntervals}           \
        I={input}                      \
        O={output}                     \
        R={genomeFasta}                \
        VALIDATION_STRINGENCY=SILENT
    """
    exshell(**vars())

ruleorder: samples__all > bam__hsMetrics

rule bam__flagstat:
  input:  "{someprefix}.bam"
  output: "{someprefix}_flagstat.txt"
  run:
    cmd = """
      samtools flagstat {input} > {output}
    """
    exshell(**vars())
