include: "bwa.py"

rule bam_bwa__alignReads:
  input: 
    configs = config__config_files,
    reads_1 = lambda wildcards: fastq__mapStringSamples(
                fastq__read, sample_read="R1", **wildcards),
    reads_2 = lambda wildcards: fastq__mapStringSamples(
                fastq__read, sample_read="R2", **wildcards)
  output:
    primary   = bam__sample
  run:
    cmd = """
      bwa mem               \
        -R "{readGroup}"    \
        -t {bwa.cores}      \
        {bwaGenomeIndex}    \
        {reads}             \
        > {output.primary}
    """
    exshell(
      input, output, cmd, **wildcards,
      readGroup = bam__sampleReadGroup(wildcards),
      bwa = pipeman.config.pipeline.modules.mapping.aligner,
      bwaGenomeIndex = bam_bwa__genomeIndex(),
      reads = bam_bwa__readsToString(input.reads_1, input.reads_2)
    )
