include: "bwa.py"

rule bam_bwa__alignReads:
  input: 
    reads_1 = pipeman.input(fastq__read, sample_read="R1"),
    reads_2 = pipeman.input(fastq__read, sample_read="R2")
  output:
    bam     = pipeman.temp(bam__sample)
  run:
    readGroup = bam__sampleReadGroup(wildcards)
    bwa       = pipeman.config.pipeline.modules.mapping.aligner
    bwaGnmIdx = bam_bwa__genomeIndex()
    reads     = bam_bwa__readsToString(input.reads_1, input.reads_2)

    cmd = """
      bwa mem               \
        -R "{readGroup}"    \
        -t {bwa.cores}      \
        {bwaGnmIdx}         \
        {reads}             \
        > {output.bam}
    """
    exshell(**vars())

ruleorder: samples__runs > bam_bwa__alignReads 
