include: "bwa.py"

rule bam_bwa__alignReads:
  input: 
    reads_1 = pipeman.input(fastq__read, sample_read="R1"),
    reads_2 = pipeman.input(fastq__read, sample_read="R2"),
    idxDir  = bam_bwa__indexDir(),
  output:
    bam     = pipeman.temp(f"{bam_mapper__sampleTarget}.bam")
  run:
    readGroup = bam__sampleReadGroup(wildcards)
    bwa       = pipeman.config.pipeline.modules.mapping.aligner
    reads     = bam_bwa__readsToString(input.reads_1, input.reads_2)
    idxPref   = bam_bwa__indexPrefix()
    cmd = """
      bwa mem                \
        -R "{readGroup}"     \
        -t {bwa.cores}       \
        {idxPref}            \
        {reads}              \
    | samtools view          \
        -Su                  \
        > {output.bam}
    """
    exshell(**vars())

rule bam_bwa__index:
  input:
    fa     = genome__fasta(),
  output:
    idxDir = directory(bam_bwa__indexDir()),
  run:
    idxPref = bam_bwa__indexPrefix()
    cmd = """
      mkdir -p {output.idxDir}
      bwa index      \
        -a bwtsw     \
        -p {idxPref} \
        {input.fa}
    """
    exshell(**vars())
ruleorder: samples__runs > bam_bwa__alignReads 
