rule counts__umi:
  input:
    bam    = f"{counts_umi__pipeDir}/{{sample_name}}.bam",
    bai    = f"{counts_umi__pipeDir}/{{sample_name}}.bai"
  output:
    counts = f"{counts_umi__pipeSample}.counts.tsv.gz"
  run:
    cmd = """
      umi_tools count            \
        --per-gene               \
        --gene-tag=XT            \
        --assigned-status-tag=XS \
        --per-cell               \
        -I {input.bam}           \
        -S {output.counts}
    """
    exshell(**vars())
