# vim syntax: python
rule env_yaml:
  output: 
    "outputs/env_yaml"
  conda:
    "envs/env_yaml.yaml"
  shell:"""
    echo "[env_yaml]"
    echo "Conda env: $(conda info -e | grep '*')"
    echo "Conda packages: $(conda list | wc -l)"
    conda list
    python -c "import yaml; print(yaml.__file__)"
    touch {output}
  """

rule env_addict:
  output: 
    "outputs/env_addict"
  conda:
    "envs/env_addict.yaml"
  shell:"""
    echo "[env_addict]"
    echo "Conda env: $(conda info -e | grep '*')"
    echo "Conda packages: $(conda list | wc -l)"
    conda list
    python -c "import addict; print(addict.__file__)"
    touch {output}
  """

rule env_none:
  output: "outputs/env_none"
  conda: "envs/env_none.yaml"
  shell:"""
    echo "[env_none]"
    echo "Conda env: $(conda info -e | grep '*')"
    echo "Conda packages: $(conda list | wc -l)"
    touch {output}
  """
