vcf__pipeTarget   = f"{bam__pipeTarget}varcall"
vcf__sampleTarget = f"{vcf__pipeTarget}/{{sample_name}}"

rule varcall__freebayes:
  input:
    bams = pipeman.input(
             f"{bam__sampleTarget}.bam",
             derefKwargs = ['sample_name',]),
    ref_genome_fa = lambda x: genome__fasta()
  output:
    vcf = f"{vcf__sampleTarget}.fb.vcf.gz"
  run:
    cmd = f"""
      freebayes -f {input.ref_genome_fa}  \
        -F 0.2                            \
        -C 2                              \
        -q 20                             \
        -m 1                              \
        --genotype-qualities              \
        --min-repeat-entropy 1            \
        --report-genotype-likelihood-max  \
        -b {input.bams}                   \
       | vcfsort                          \
       | vcfuniq                          \
       | vcfsort                          \
       | vcffixup -                       \
       | bgzip -fc                        \
       > {output.vcf}
    """
    exshell(**vars())

rule varcall__filter:
  input:
    vcf = f"{vcf__sampleTarget}.fb.vcf.gz"
  output:
    vcf = f"{vcf__sampleTarget}.fb.filter.vcf.gz"
  run:
    cmd = f"""
      zcat {input.vcf}  \
      | snpSift filter  "( QUAL > 0 ) & ( QUAL / AO > 1 ) & ( SAF > 0 & SAR > 0 ) & ( RPR > 1 & RPL > 1 ) & ( MQM > 10 | MQMR > 10 )" \
      | bgzip -c > {output.vcf}
      tabix -f {output.vcf}
    """
    exshell(**vars())
