# ---------------
# Merging Reads
# ---------------
rule fastq_merging__mergeReads:
  """
  Merges sample reads filtered by the given wildcards.
  """
  input:
    reads = pypette.input(fastq__chunk)
  output:
    read  = pypette.temp(fastq_merge__read)
  run:
    input.reads.sort()

    if len(input.reads) == 1:
      cmd = """
        ln.rel {input.reads[0]} {output.read}
      """
    else:
      cmd = f"""
        zcat {input.reads} \
         | gzip            \
         > {output.read}
      """
      cmd = f"""
        zcat {input.reads} | gzip > {output.read}
      """
    exshell(**vars())

ruleorder: samples__runs > fastq_merging__mergeReads
