rule fastq_qc__reads:
  """
  Produces a Fastqc report for whatever the given fastq reads.
  """
  input: 
    fastq = "{path}.fastq.gz"
  output:
    html  = "{path}" + fastq_qc__htmlExt,
    zip   = "{path}" + fastq_qc__zipExt
  run:
    fastqc = pypette.config.pipeline.modules.fastq.qc.fastqc
    cmd = """
      fastqc -t {fastqc.cores} {input}
    """
    exshell(**vars())

ruleorder: samples__runs > fastq_qc__reads
