trimmingTools = ('trimmomatic', 'cutadapt')
pipeman.updateWildcardConstraints(
  procTrimming = "(trimmed/({})/)?".format('|'.join(trimmingTools)),
)

rule fastq_trimming__trimmomatic:
  input: "{someprefix}/{fastq}.fastq.gz"
  output: "{someprefix}/trimmed/trimmomatic/{fastq}.fastq.gz"
  run:
    cmd = """
      echo "{rule}: from '{input}' to '{output}'."
    """
    exshell(input, output, cmd, rule=rule, **wildcards)

rule fastq_trimming__cutadapt:
  input: "{someprefix}/{fastq}.fastq.gz"
  output: "{someprefix}/trimmed/cutadapt/{fastq}.fastq.gz"
  run:
    cmd = """
      echo "{rule}: from '{input}' to '{output}'."
    """
    exshell(input, output, cmd, rule=rule, **wildcards)
