pipeline:
  name: 'rnaseq'
  modules:
    mapping:
      aligner:
        name: "STAR"
        command: "STAR"
        version: "STAR_2.5.3a"
        cores: 6
        ram: '32gb'
        outFilterMismatchNmax: 10
      counter:
        name: "featureCounts"
        version: "1.6.2"
        cores: 4
    fastq:
      qc:
        fastqc:
          cores: 6
      trimming:
        trimmers:
          trimmomatic:
            mem: '10gb'
            memJava: '10240M'
            headcrop: 'HEADCROP:12'
          cutadapt:
          bbduk:
      adapters:
        base: &baseAdapters "Adapters.fasta" 
        cutadapt: *baseAdapters
        trimmomatic: *baseAdapters
        bbduk: "BBDUK/adapters.fa"
  sampleBased: True
  deepStructure: True
  sequencing:
    platform: 'Illumina'
  center:
    name: 'CTGB'
  condactivate: False
  logCommands: True
  outDir: 'project-analysis'
