pipeline:
  name: 'rnaseq'
  modules:
    mapping:
      aligner:
        name: "STAR"
        command: "STAR"
        version: "STAR_2.5.3a"
        cores: 6
        ram: '32gb'
        outFilterMismatchNmax: 10
    fastq:
      qc:
        fastqc:
          cores: 6        
  sample_based: True
  deep_structure: True
  sequencing:
    platform: Illumina
  center:
    name: CTGB
  condactivate: True
  logCommands: True
