include: "dge.py"

dge__pipeTarget   = f"{bam__pipeTarget}dge"
dge__sampleTarget = f"{dge__pipeTarget}/{{sample_name}}"

dge__plotTarget           = f"{dge__pipeTarget}/plots"
dge__plotSampleTarget     = f"{dge__plotTarget}/{{sample_name}}"

dge__enrichTarget         = f"{dge__pipeTarget}/enrichR"
dge__enrichedSampleTarget = f"{dge__enrichTarget}/{{sample_name}}"

rule dge__plots:
  input: 
    metadata    = "samples/metadata.tsv",
    counts      = f"{bam__pipeTarget}featureCounts/{{sample_name}}.mergedCounts.gz"
  output:
    distEstims  = f"{dge__plotSampleTarget}.distEstimsPlot.png",
    maPlot      = f"{dge__plotSampleTarget}.maPlot.pdf",
    volcanoPlot = f"{dge__plotSampleTarget}.volcanoPlot.pdf",
    pheatMap    = f"{dge__plotSampleTarget}.pheatMap.png",
    pca         = f"{dge__plotSampleTarget}.pca.pdf"
  params:
    fCountsDataCols = counts__stdCols(),
    dge = lambda wildcards, input: dge__deseq2ParamsDft(input.metadata)
  script: 
    pipeman.rscript("dge/plots.R")

rule dge__enrichR:
  input: 
    metadata    = "samples/metadata.tsv",
    counts      = f"{bam__pipeTarget}featureCounts/{{sample_name}}.mergedCounts.gz"
  output:
    dir = directory(f"{dge__enrichTarget}")
  params:
    fCountsDataCols = counts__stdCols(),
    dge = lambda wildcards, input: dge__deseq2ParamsDft(input.metadata)
  script: 
    pipeman.rscript("dge/enrichR.R")
