""" Pipeline Configuration """
pypette.includeModules(
  "config/config.sk",
  "config/seqrun.sk",
)
pypette.loadConfigFiles()

""" 
Pipeline Workflow 
Loaded only if required configuration files are present.
"""
pypette.includeModules(
  "qc/seqrun.sk",
  withConfigFiles=True)
