""" Pipeline Configuration """
pipeman.includeModules(
  "config/config.sk",
  "config/seqrun.sk",
)
pipeman.loadConfigFiles()

""" 
Pipeline Workflow 
Loaded only if required configuration files are present.
"""
pipeman.includeModules(
  "qc/seqrun.sk",
  withConfigFiles=True)
