pipeline:
  name: 'rnaseq'
  modules:
    fastq:
      qc:
        fastqc:
          cores: 6
      trimming:
        trimmers:
          trimmomatic:
            cores: 8
            mem: '10gb'
            memJava: '10240M'
            headcrop: 'HEADCROP:12'
          cutadapt:
          bbduk:
            cores: 8
            mem: '10gb'
      adapters:
        base: &baseAdapters "Adapters.fasta" 
        cutadapt: *baseAdapters
        trimmomatic: *baseAdapters
        bbduk: "BBDUK/adapters.fa"
  sequencing:
    platform: 'Illumina'
  center:
    name: 'CTGB'
  logCommands: True
  outDir: 'projects'
  tempFiles: 'kept-temp-files.txt'
