""" Pipeline Configuration """
pypette.includeModules(
  "config/config.sk",
  "config/project.sk",
  "config/samples.sk"
)
pypette.loadConfigFiles()

""" 
Pipeline Workflow.
Modules are loaded only if required configuration files above are present.
"""
pypette.includeModules(
  "fastq/fastq.sk",
  "qc/fastqc.sk",
  withConfigFiles=True)
