multiqc__dir          = "multiqc"
multiqc__report       = "samples/all/" + bam__pipelineDir + "report.html"

rule multiqc__report:
  input:
    fastqcs  = lambda wildcards: fastq__mapStringSamples(
      fastq_qc__readZip, **wildcards),
    bamstats = lambda wildcards: fastq__mapStringSamples(
      bam__mergedSampleStats, **wildcards)
  output:
    report   = multiqc__report
  run:
    dirs = [ os.path.dirname(d) for d in input ]
    cmd  = """
      multiqc              \
        -o {multiqc__dir}  \
        {input}            \
        -n {output.report}
    """
    exshell(input, output, cmd, 
      multiqc__dir=multiqc__dir,
      **wildcards)
