import utils.dicts

# ---------------
# Metadata file
# ---------------
lims__SRV_URL="f2.ricerca.hsr.it"
lims__PRJ_URL = lims__SRV_URL + "/projects"
lims__SEQU_RUN_URL = lims__PRJ_URL + "/api/sequencing_run"
lims__TO_DEMUX_URL = lims__SEQU_RUN_URL + "/to_demultiplex/"

lims__project_medata_io_format = "json"
lims__project_metadata_io = (
  "{prj_name}/metadata.{format}"
    .format_map(utils.dicts.Default({ 'format': lims__project_medata_io_format,}))
)
rule lims__projectMetadata:
  output: 
    primary = lims__project_metadata_io

  shell:"""
    curl                                                                      \
      --fail                                                                  \
      "{lims__PRJ_URL}/{wildcards.prj_name}.{lims__project_medata_io_format}" \
     > {output.primary}
  """

# PRJ=AgrestiA_825_Agresti_KIZILIRMAK_Cise_RNA
# ctgb-pipe -p rnaseq -o lims__createProject_${PRJ}.done
rule lims__createProject:
  input:
    primary = lims__project_metadata_io
  output:
    "lims__createProject_{prj_name}.done"

  run:
    pipeman.config_manager.loadConfig(input.primary)
    shell("""
      touch {output}
    """)
    
pipeman.toClean("lims__*.done")
