pipeline:
  rnaseq:
    modules:
      star:
        command: "Star"
        version: "STAR_2.5.3a"
        cores: 6
        ram: '32gb'
        outFilterMismatchNmax: 10
      fastqc:
        cores: 6        
