""" Pipeline Configuration """
pypette.includeModules(
  "config/config.sk",
  "config/project.sk",
  "config/samples.sk"
)
pypette.loadConfigFiles()

""" 
Pipeline Workflow 
Loaded only if required configuration files are present.
"""
pypette.includeModules(
  "fastq/fastq.sk",
  "bam/bam.sk",
  "qc/dna.sk",
  "varcall/varcall.sk",
  "varcall/freebayes.sk",
  "varcall/gatk.sk",
  withConfigFiles=True)
