#!/usr/bin/env python
include: "pokemon.py"

rule poke:
  """
  Presents a sample.
  """
  output: "{p}.poke"
  run:
    print(msgPoke(getPokeDict(wildcards.p)))
    open(output[0], 'a').close()

rule evol:
  """
  Describes an evolution.
  """
  input: "{p}.poke"
  output: "{p}.evol"
  run:
    print(msgEvol(getPokeDict(wildcards.p)))
    open(output[0], 'a').close()

rule evols:
  """
  Describes all evolutions.
  """
  input: "{p}.poke"
  output: "{p}.evols"
  run:
    print(msgEvols(getPokeDict(wildcards.p)))
    open(output[0], 'a').close()

pipman.toClean("*.poke", "*.evol", "*.evols")
