pipeline:
  name: 'wes'
  modules:
    mapping:
      aligner:
        name: "bwa"
        command: "bwa"
        version: "0.7.15-r1140"
        cores: 6
        ram: '32gb'
    fastq:
      qc:
        fastqc:
          cores: 6        
      trimming:
        trimmers:
          trimmomatic:
            mem: '10gb'
            memJava: '10240M'
            headcrop: ''
          cutadapt:
          bbduk:
      adapters:
        base: &baseAdapters "Adapters.fasta"
        cutadapt: *baseAdapters
        trimmomatic: *baseAdapters
        bbduk: "BBDUK/adapters.fa"
  sampleBased: True
  deepStructure: True
  sequencing:
    platform: Illumina
  center:
    name: CTGB
  condactivate: True
  logCommands: True
