pipeline:
  name: 'wes'
  modules:
    mapping:
      aligner:
        name: "bwa"
        command: "bwa"
        version: "0.7.17-r1188"
        cores: 6
        ram: '64gb'
      counter:
        name: "featureCounts"
        version: "1.6.4"
        cores: 4
      sorter:
        picard:
          cores: 4
          mem: '12gb'
        samtools:
          cores: 4
          mem: '12gb'
      markdup:
        cores: 4
        mem: '12gb'
    fastq:
      qc:
        fastqc:
          cores: 6        
      trimming:
        trimmers:
          trimmomatic:
            cores: 8
            mem: '10gb'
            memJava: '10240M'
            headcrop: 
          cutadapt:
          bbduk:
            cores: 8
            mem: '10gb'
      adapters:
        base: &baseAdapters "Adapters.fasta"
        cutadapt: *baseAdapters
        trimmomatic: *baseAdapters
        bbduk: "BBDUK/adapters.fa"
  sampleBased: True
  deepStructure: True
  sequencing:
    platform: 'Illumina'
  center:
    name: 'CTGB'
  condactivate: False
  logCommands: True
  outDir: 'project-analysis'
