pipeline:
  name: 'rnaseq'
  modules:
    mapping:
      bwa:
        command: "bwa"
        version: "0.7.15-r1140"
        cores: 6
        ram: '32gb'
        outFilterMismatchNmax: 10
    fastq:
      qc:
        fastqc:
          cores: 6        
  sample_based: True
  deep_structure: True
  sequencing:
    platform: Illumina
  center:
    name: CTGB
