biotypes__pipeTarget   = f"{bam__pipeTarget}biotypes"
biotypes__sampleTarget = f"{biotypes__pipeTarget}/{{sample_name}}"

""" Assesses and plots biotypes distributions """
rule biotypes:
  input: 
    counts   = pipeman.input(f"{bam__sampleTarget}.mergedCounts.gz"),
    biotypes = gencode__biotypes()
  output:
    pngs     = directory(f"{biotypes__sampleTarget}_pngs")
  params: 
    biotypes = pipeman.config.pipeline.modules.biotypes,
  script:
    "plot-biotypes.R"
