include: "genome.py"

rule genome__fa:
  input:
    fa  = "{someprefix}.fa.gz"
  output:
    fa  = pypette.temp("{someprefix}.fa")
  run:
    cmd = """
      gunzip -c {input.fa} > {output.fa}
    """
    exshell(**vars())

rule genome__fai:
  input:
    fa   = "{someprefix}.fa"
  output:
    fai  = pypette.temp("{someprefix}.fa.fai")
  run:
    cmd = """
      samtools faidx {input.fa} > {output.fai}
    """
    exshell(**vars())

rule genome__ebiFaGz:
  output:
    fa  = genome__ebiFastaGz()
  run:
    cmd = f"""
      curl "{genome__ebiFastaUrl()}" -o {output.fa}
    """
    cmd, force = cmdOrLink(
                   cmd,
                   genome__ebiFastaGz(sharedDir=True),
                   output.fa)
    exshell(**vars())

rule genome__ucscFa:
  input:
    bit = genome__ucsc2bit()
  output:
    fa  = genome__ucscFasta()
  run:
    cmd = """
      twoBitToFa {input.bit} {output.fa}
    """
    exshell(**vars())

rule genome__ucsc2bit:
  output:
    bit = genome__ucsc2bit()
  run:
    cmd = f"""
      curl "{genome__ucsc2bitUrl()}" -o {output.bit}
    """
    cmd, force = cmdOrLink(
                   cmd, 
                   genome__ucsc2bit(sharedDir=True), 
                   output.bit)
    exshell(**vars())
