include: "genome.py"

rule genome__fa:
  input:
    bit = genome__2bit()
  output:
    fa  = genome__fasta()
  run:
    cmd = """
      twoBitToFa {input.bit} {output.fa}
    """
    exshell(**vars())

rule genome__2bit:
  output:
    bit = genome__2bit()
  run:
    shared = genome__2bit(sharedDir=True, withFile=True)
    if shared:
      cmd = f"""
        ln -s {shared} {output.bit}
      """
    else:
      url = genome__ucsc2bitUrl()
      cmd = """
        curl              \
          {url}           \
          -o {output.bit}
      """
    exshell(**vars())
