include: "samples.py"

rule samplenames:
  """
  List all sample names.
  """
  run:
    print(pipeman.samples.data['sample_name'])

rule samples:
  """
  List all samples.
  """
  run:
    print(pipeman.samples.data)

# -----------
# Wildcards
# -----------
rule samples__runs:
  input: lambda wildcards:
    fastq__mapStringSamples('samples/{sample_name}/runs/{sample_run}', **wildcards)
  output:
    "samples/{sample_name}/runs/all{suffix}"
  run:
    cmd = """
      touch {output}
    """
    texshell(**vars())

rule samples__all:
  input: lambda wildcards:
    fastq__mapStringSamples("samples/{sample_name}", **wildcards)
  output:
    "samples/all{suffix}"
  run:
    cmd = """
      touch {output}
    """
    texshell(**vars())

ruleorder: samples__all > samples__runs
