include: "config.sk"

localrules: pbs_dir, update_cluster_rules
rule pbs_dir:
    output:
        primary= {PBS_DIR}
    shell:"""
      mkdir -p {PBS_DIR}
    """ 

yaml = "cluster.yaml"
rule update_cluster_rules:
    #
    # Looks for all the pipeline's available rules write default cluster configuration
    # in the 'yaml' file.
    #
    #output: primary = yaml
    run:
        shell("""
      ## Update default:
      if [ ! -f "{yaml}" ] || ! grep -s -q "^__default__:" "{yaml}"; then
        cat << HERE > "{yaml}"
__default__:
  name: '{tmp_name}'
  select: 1
  ncpus: 1
  mem: '1gb'
  error: '{tmp_primary}.pbs.err' 
  output: '{tmp_primary}.pbs.out'
HERE
      fi

      # Update rules if not here
      for _rule in {_rules}; do
        grep -s -q "^$_rule" "{yaml}" \
         || cat << HERE >> "{yaml}"
$_rule:
  do: True
HERE
      done
    """.format(yaml=yaml, _rules=" ".join(rules.__dict__.keys()), 
               tmp_name = "{{config[project][type]}}",
               tmp_primary = "{{output.primary}}"
    ))
