pipeline:
  name: 'scrna'
  javaXmx: &javaXmx '32g'
  modules:
    mapping:
      aligner:
        name: "STAR"
        command: "STAR"
        version: "STAR_2.5.3a"
        cores: 6
        ram: '64gb'
        outFilterMismatchNmax: 10
      counter:
        name: "featureCounts"
        version: "1.6.4"
        cores: 4
      sorter:
        picard:
          cores: 4
          mem: '12gb'
        samtools:
          cores: 4
          mem: '12gb'
      markdup:
        cores: 4
        mem: '12gb'
    fastq:
      qc:
        fastqc:
          cores: 6
      trimming:
        trimmers:
          trimmomatic:
            cores: 8
            mem: '10gb'
            javaXmx: *javaXmx
            headcrop: 0
          cutadapt:
            cores: 8
          bbduk:
            cores: 8
            mem: '10gb'
      adapters:
        base: &baseAdapters "Adapters.fasta" 
        cutadapt: *baseAdapters
        trimmomatic: *baseAdapters
        bbduk: "BBDUK/adapters.fa"
      umi:
        bcPattern: 'CCCCCCCCCCCCCCCCNNNNNNNNNNNN'
        setCellNumber: False
        cellNumber: 1000
    markerGenes:
      scanpy:
        verbosity: 3
        firstFilter:
          minGenes: 50
          minCells: 5 
        secondFilter:
          nGenes: 8000
          percentMito: 0.25
        normalization:
          countPerCellAfter: 10000
          highVarGen_minMean: 0.0125
          highVarGen_maxMean: 3
          highVarGen_minDisp: 0.5
          scale_maxVal: 10
        cellCycleScore:
          useOnlyHighlyVariable: True
          regressOnCellCycle: True
        plot:
          keepOnlyHVG: True
        louvain:
          nNeighbors: 10
          resolution: 0.4
        tsne:
          nPC: 20
          randomState: 2
        clusterMarkers:
          method: 't-test' #'logreg', 't-test', 'wilcoxon', 't-test_overestim_var'
          plot_nGenes: 20
          useRaw: True 
          logValue: True
          minInGroupFraction: 0.25
          minFoldChange: 1.19
          maxOutGroupFraction: 0.5
          newClusterNames: [] # a list with the names for the clusters, sorted from cluster 0 to max  for example: ['CD4 T', 'CD14 Monocytes','B', 'CD8 T','NK', 'FCGR3A Monocytes','Dendritic', 'Megakaryocytes']
          showGeneLabelsInHeatmap: False
          stackedViolinTopGenes: 2 # 2 or 3 for top 2 or top 3 markers genes in stackedViolinPlot
          dotTopGenes: 2 # 2 or 3 for top 2 or top 3 markers genes in dotPlot
          markerGenesDict: {} # dictionary to characterize cell types in dotPlot. Choose custom marker genes. For example: {'B-cell': ['CD79A', 'MS4A1'],'T-cell': 'CD3D','T-cell CD8+': ['CD8A', 'CD8B'],'NK': ['GNLY', 'NKG7'],'Myeloid': ['CST3', 'LYZ'],'Monocytes': ['FCGR3A'],'Dendritic': ['FCER1A']}
  sequencing:
    platform: 'Illumina'
  center:
    name: 'CTGB'
  logCommands: True
  outDir: 'projects'
  tempFiles: 'kept-temp-files.txt'
