""" Pipeline Configuration """
pypette.includeModules(
  "config/config.sk",
  "config/project.sk",
  "config/samples.sk"
)
pypette.loadConfigFiles()

""" 
Pipeline Workflow.
Modules are loaded only if required configuration files above are present.
"""
pypette.includeWorkflow(
  "fastq/fastq",
  "fastq/merge",
  "fastq/qc",
  "fastq/umi-extract",
  "bam/bam",
  "bam/star",
  "qc/rseqc", # required for bam/counts
  "bam/counts",
  "bam/counts-umi",
  "markerGenes/scanpy",
)
