import os
import sys
sys.path = os.environ['_CPIPE_PYTHON_SYSPATH'].split()
from utils import environ, pipeline

""" Define the pipeline manager """
pipeman = pipeline.PipelineManager(namespace=globals())

""" Include core modules """
pipeman.includeModule('core/core.sk')

""" Include requested pipeline """
include: pipeman.pipeSnake
