import os
import sys
sys.path = os.environ['_PYPETTE_PYTHON_SYSPATH'].split()
from utils import environ, pipeline

""" Define the pipeline manager """
pypette = pipeline.PipelineManager(namespace=globals())

""" Include core modules """
pypette.includeModule('core/core.sk')

""" Include requested pipeline """
include: pypette.pipeSnake
